optimizers:
  trunk_optimizer:
    RMSprop:
      lr: 0.000001
      weight_decay: 0.0001
      momentum: 0.9
  embedder_optimizer:
    RMSprop:
      lr: 0.000001
      weight_decay: 0.0001
      momentum: 0.9
