eval_reference_set: compared_to_self
eval_normalize_embeddings: True
eval_use_trunk_output: False
eval_batch_size: 32
eval_primary_metric: mean_average_precision_at_r
eval_dataloader_num_workers: 2
eval_pca: null
eval_size_of_tsne: 0
