eval_k: 100
eval_reference_set: compared_to_self
eval_normalize_embeddings: True
eval_use_trunk_output: False
eval_batch_size: 32
eval_metric_for_best_epoch: recall_at_1
eval_dataloader_num_workers: 2

