training_method: MetricLossOnly
testing_method: GlobalEmbeddingSpaceTester
meta_testing_method: ConcatenateEmbeddings

dataset:  
  Logos:
num_epochs_train: 2
iterations_per_epoch: 10
save_interval: 2

special_split_scheme_name: null
test_size: 0.4
test_start_idx: 0.2
num_training_partitions: 2
num_training_sets: 2

label_hierarchy_level: 0
dataloader_num_workers: 0
check_untrained_accuracy: True
patience: null
