training_method: MetricLossOnly
testing_method: GlobalEmbeddingSpaceTester
dataset:  
  CUB200:
num_epochs_train: 4
iterations_per_epoch: 100
save_interval: 2

special_split_scheme_name: null
test_size: 0.5
test_start_idx: 0.5
num_training_partitions: 5
num_training_sets: 5

label_hierarchy_level: 0
dataloader_num_workers: 4
skip_eval: False
check_untrained_accuracy: False
patience: null
