dataset:
  CUB200:

multi_dataset: null

splits_to_eval:
  - val

split_manager:
  ClassDisjointSplitManager:
    test_size: 0.5
    test_start_idx: 0.5
    num_training_partitions: 4
    num_training_sets: 4
    hierarchy_level: 0
    data_and_label_getter_keys: [data, label]

label_hierarchy_level: 0