models:
  trunk:
    inception_v3:
      pretrained: True
  embedder:
    MLP:
      layer_sizes:
        - 128
batch_size: 80
freeze_batchnorm: True
layers_to_extract:
  - Mixed_5d
  - Mixed_6e
  - fc