transforms:
  eval:
    Resize:
      size: 256
    CenterCrop:
      size: 227

  augmentation1:
    Resize:
      size: 256
    RandomResizedCrop:
      scale: 0.16 1
      ratio: 0.75 1.33
      size: 227
    RandomHorizontalFlip:
      p: 0.5
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0.5
    RandomGrayscale: {}

  augmentation2:
    Resize:
      size: 256
    RandomResizedCrop:
      scale: 0.16 1
      ratio: 0.75 1.33
      size: 227
    RandomHorizontalFlip:
      p: 0.5
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0.5
    RandomGrayscale: {}

  augmentation3:
    Resize:
      size: 256
    RandomResizedCrop:
      scale: 0.16 1
      ratio: 0.75 1.33
      size: 227
    RandomHorizontalFlip:
      p: 0.5
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0.5
    RandomGrayscale: {}