trainer: 
  MetricLossOnly:
    iterations_per_epoch: 100
    dataloader_num_workers: 2
    batch_size: 32
    freeze_trunk_batchnorm: True
    label_hierarchy_level: 0
    loss_weights: null
    set_min_label_to_zero: True

meta_testing_method: 
  - meta_SeparateEmbeddings
  - meta_ConcatenateEmbeddings

num_epochs_train: 1000
save_interval: 2
patience: 9

check_untrained_accuracy: True
skip_eval_if_already_done: True
skip_meta_eval_if_already_done: True
save_figures_on_tensorboard: False
save_lists_in_db: False